apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-test-deployment
  template:
    metadata:
      labels:
        app: stress-test-deployment
    spec:
      containers:
      - name: stress-test
        image: cagataykahraman/alpine-stress-tool
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
